// Code generated by ipc/codegen/generate.go; DO NOT EDIT.
package wails

import "time"

type InstanceDTO struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	GameVersion      string `json:"game_version"`
	Loader           string `json:"loader"`
	LoaderVersion    string `json:"loader_version,omitempty"`
	IconPath         string `json:"icon_path,omitempty"`
	State            string `json:"state"`
	TotalPlaySeconds int64  `json:"total_play_seconds"`
}

type CreateInstanceRequest struct {
	Name        string `json:"name"`
	GameVersion string `json:"game_version"`
	Loader      string `json:"loader"`
}

type LaunchResponse struct {
	Success bool   `json:"success"`
	PID     int    `json:"pid,omitempty"`
	Error   string `json:"error,omitempty"`
}

type DownloadProgressEvent struct {
	TaskID     string  `json:"task_id"`
	FileName   string  `json:"file_name"`
	BytesRead  int64   `json:"bytes_read"`
	TotalBytes int64   `json:"total_bytes"`
	Percentage float64 `json:"percentage"`
	SpeedBPS   int64   `json:"speed_bps"`
}

type LogLineEvent struct {
	InstanceID string    `json:"instance_id"`
	Level      string    `json:"level"`
	Message    string    `json:"message"`
	Timestamp  time.Time `json:"timestamp"`
}
