// Code generated by ipc/codegen/generate.go; DO NOT EDIT.
package wails

import "time"

type InstanceDTO struct {
	ID               string     `json:"id"`
	Name             string     `json:"name"`
	GameVersion      string     `json:"game_version"`
	Loader           string     `json:"loader"`
	LoaderVersion    string     `json:"loader_version,omitempty"`
	IconPath         string     `json:"icon_path,omitempty"`
	JavaPath         string     `json:"java_path,omitempty"`
	MinRAMMB         int        `json:"min_ram_mb"`
	MaxRAMMB         int        `json:"max_ram_mb"`
	JVMArgs          []string   `json:"jvm_args"`
	SkipJavaCheck    bool       `json:"skip_java_check"`
	State            string     `json:"state"`
	LastPlayedAt     *time.Time `json:"last_played_at,omitempty"`
	TotalPlaySeconds int64      `json:"total_play_seconds"`
}

type CreateInstanceRequest struct {
	Name        string `json:"name"`
	GameVersion string `json:"game_version"`
	Loader      string `json:"loader"`
	JavaPath    string `json:"java_path,omitempty"`
}

type UpdateInstanceRequest struct {
	ID            string   `json:"id"`
	Name          string   `json:"name,omitempty"`
	JavaPath      string   `json:"java_path,omitempty"`
	ClearJavaPath bool     `json:"clear_java_path,omitempty"`
	MinRAMMB      int      `json:"min_ram_mb,omitempty"`
	MaxRAMMB      int      `json:"max_ram_mb,omitempty"`
	JVMArgs       []string `json:"jvm_args,omitempty"`
	SkipJavaCheck *bool    `json:"skip_java_check,omitempty"`
}

type LaunchResponse struct {
	Success bool   `json:"success"`
	PID     int    `json:"pid,omitempty"`
	Error   string `json:"error,omitempty"`
}

type AccountDTO struct {
	UUID     string `json:"uuid"`
	Username string `json:"username"`
	Type     string `json:"type"`
	IsActive bool   `json:"is_active"`
}

type ModItemDTO struct {
	ID         string   `json:"id"`
	Slug       string   `json:"slug"`
	Source     string   `json:"source"`
	Name       string   `json:"name"`
	Author     string   `json:"author"`
	Summary    string   `json:"summary"`
	IconURL    string   `json:"icon_url,omitempty"`
	Downloads  int64    `json:"downloads"`
	Categories []string `json:"categories"`
}

type InstalledModDTO struct {
	FileName    string `json:"file_name"`
	ModID       string `json:"mod_id,omitempty"`
	Name        string `json:"name"`
	Version     string `json:"version,omitempty"`
	Source      string `json:"source,omitempty"`
	ReleaseType string `json:"release_type,omitempty"`
	Enabled     bool   `json:"enabled"`
	SizeBytes   int64  `json:"size_bytes"`
}

type CrashReportDTO struct {
	Category      string   `json:"category"`
	Summary       string   `json:"summary"`
	Remedy        string   `json:"remedy"`
	Details       string   `json:"details"`
	RelevantLines []string `json:"relevant_lines"`
	ExitCode      int      `json:"exit_code"`
}

type SearchModsRequest struct {
	Query       string `json:"query"`
	GameVersion string `json:"game_version"`
	Loader      string `json:"loader"`
	Source      string `json:"source"`
	Limit       int    `json:"limit"`
	Offset      int    `json:"offset"`
	Sort        string `json:"sort,omitempty"`
	Category    string `json:"category,omitempty"`
}

type SearchModsResultDTO struct {
	Items             []ModItemDTO `json:"items"`
	TotalCount        int64        `json:"total_count"`
	Reason            string       `json:"reason,omitempty"`
	RetryAfterSeconds int          `json:"retry_after_seconds,omitempty"`
}

type ToggleModRequest struct {
	InstanceID string `json:"instance_id"`
	FileName   string `json:"file_name"`
	Enable     bool   `json:"enable"`
}

type DeleteModRequest struct {
	InstanceID string `json:"instance_id"`
	FileName   string `json:"file_name"`
}

type DownloadProgressEvent struct {
	TaskID     string  `json:"task_id"`
	FileName   string  `json:"file_name"`
	BytesRead  int64   `json:"bytes_read"`
	TotalBytes int64   `json:"total_bytes"`
	Percentage float64 `json:"percentage"`
	SpeedBPS   int64   `json:"speed_bps"`
}

type LogLineEvent struct {
	InstanceID string    `json:"instance_id"`
	Level      string    `json:"level"`
	Message    string    `json:"message"`
	Timestamp  time.Time `json:"timestamp"`
}

type UpdateInfoDTO struct {
	HasUpdate      bool      `json:"has_update"`
	Version        string    `json:"version"`
	CurrentVersion string    `json:"current_version"`
	ReleaseDate    time.Time `json:"release_date"`
	ReleaseNotes   string    `json:"release_notes"`
	DownloadURL    string    `json:"download_url"`
	SHA256         string    `json:"sha256"`
	Size           int64     `json:"size"`
}

type UpdateApplyResultDTO struct {
	Success         bool   `json:"success"`
	Message         string `json:"message,omitempty"`
	RestartRequired bool   `json:"restart_required,omitempty"`
}

type ListModVersionsRequest struct {
	InstanceID  string `json:"instance_id,omitempty"`
	ModID       string `json:"mod_id"`
	Source      string `json:"source"`
	GameVersion string `json:"game_version,omitempty"`
	Loader      string `json:"loader,omitempty"`
}

type ModFileDTO struct {
	ID           string   `json:"id"`
	ModID        string   `json:"mod_id"`
	FileName     string   `json:"file_name"`
	DisplayName  string   `json:"display_name"`
	ReleaseType  string   `json:"release_type"`
	FileSize     int64    `json:"file_size"`
	FileDate     string   `json:"file_date"`
	GameVersions []string `json:"game_versions"`
	Loaders      []string `json:"loaders"`
	DownloadURL  string   `json:"download_url"`
}

type ModInstallProgressDTO struct {
	TaskID     string `json:"task_id"`
	InstanceID string `json:"instance_id"`
	ModID      string `json:"mod_id"`
	FileName   string `json:"file_name"`
	Status     string `json:"status"`
	BytesRead  int64  `json:"bytes_read"`
	TotalBytes int64  `json:"total_bytes"`
	Percentage int    `json:"percentage"`
	Error      string `json:"error,omitempty"`
}

type InstallModRequest struct {
	InstanceID  string `json:"instance_id"`
	ModID       string `json:"mod_id"`
	ModSlug     string `json:"mod_slug"`
	ModName     string `json:"mod_name"`
	Source      string `json:"source"`
	GameVersion string `json:"game_version"`
	Loader      string `json:"loader"`
	VersionID   string `json:"version_id,omitempty"`
}

type InstallModResponse struct {
	Success  bool   `json:"success"`
	FileName string `json:"file_name"`
	Message  string `json:"message"`
}

type SetSettingRequest struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type GetSettingsResponse struct {
	Settings map[string]string `json:"settings"`
}

type JavaInstallationDTO struct {
	Path         string   `json:"path"`
	HomeDir      string   `json:"home_dir"`
	MajorVersion int      `json:"major_version"`
	FullVersion  string   `json:"full_version"`
	Vendor       string   `json:"vendor"`
	Kind         string   `json:"kind"`
	UsedBy       []string `json:"used_by"`
}

type JavaDownloadStatusDTO struct {
	TaskID     string  `json:"task_id"`
	Major      int     `json:"major"`
	Status     string  `json:"status"`
	BytesRead  int64   `json:"bytes_read"`
	TotalBytes int64   `json:"total_bytes"`
	Percentage float64 `json:"percentage"`
	Error      string  `json:"error,omitempty"`
}
