// Code generated by ipc/codegen/generate.go; DO NOT EDIT.

export type LoaderType = "vanilla" | "fabric" | "quilt" | "forge" | "neoforge";
export type InstanceState = "idle" | "downloading" | "launching" | "running" | "crashed";
export type AccountType = "microsoft" | "offline";
export type ModSource = "modrinth" | "curseforge";

export interface InstanceDTO {
  id: string;
  name: string;
  game_version: string;
  loader: LoaderType;
  loader_version?: string;
  icon_path?: string;
  state: InstanceState;
  total_play_seconds: number;
}

export interface CreateInstanceRequest {
  name: string;
  game_version: string;
  loader: LoaderType;
}

export interface LaunchResponse {
  success: boolean;
  pid?: number;
  error?: string;
}

export interface AccountDTO {
  uuid: string;
  username: string;
  type: AccountType;
  is_active: boolean;
}

export interface ModItemDTO {
  id: string;
  slug: string;
  source: ModSource;
  name: string;
  author: string;
  summary: string;
  icon_url?: string;
  downloads: number;
  categories: string[];
}

export interface InstalledModDTO {
  file_name: string;
  mod_id?: string;
  name: string;
  version?: string;
  enabled: boolean;
  size_bytes: number;
}

export interface CrashReportDTO {
  category: string;
  summary: string;
  remedy: string;
  details: string;
  relevant_lines: string[];
  exit_code: number;
}

export interface SearchModsRequest {
  query: string;
  game_version: string;
  loader: string;
  source: ModSource;
  limit: number;
  offset: number;
}

export interface ToggleModRequest {
  instance_id: string;
  file_name: string;
  enable: boolean;
}

export interface DeleteModRequest {
  instance_id: string;
  file_name: string;
}

export interface DownloadProgressEvent {
  task_id: string;
  file_name: string;
  bytes_read: number;
  total_bytes: number;
  percentage: number;
  speed_bps: number;
}

export interface LogLineEvent {
  instance_id: string;
  level: "info" | "warn" | "error" | "debug";
  message: string;
  timestamp: string;
}

export interface UpdateInfoDTO {
  has_update: boolean;
  version: string;
  current_version: string;
  release_date: string;
  release_notes: string;
  download_url: string;
  sha256: string;
  size: number;
}

export interface UpdateApplyResultDTO {
  success: boolean;
  message?: string;
  restart_required?: boolean;
}

export interface InstallModRequest {
  instance_id: string;
  mod_id: string;
  mod_slug: string;
  mod_name: string;
  source: ModSource;
  game_version: string;
  loader: string;
}

export interface InstallModResponse {
  success: boolean;
  file_name: string;
  message: string;
}

export interface SetSettingRequest {
  key: string;
  value: string;
}

export interface GetSettingsResponse {
  settings: Record<string, string>;
}
