// Code generated by ipc/codegen/generate.go; DO NOT EDIT.

export type LoaderType = "vanilla" | "fabric" | "quilt" | "forge" | "neoforge";
export type InstanceState = "idle" | "downloading" | "launching" | "running" | "crashed";
export type AccountType = "microsoft" | "offline";
export type ModSource = "modrinth" | "curseforge";

export interface InstanceDTO {
  id: string;
  name: string;
  game_version: string;
  loader: LoaderType;
  loader_version?: string;
  icon_path?: string;
  java_path?: string;
  min_ram_mb: number;
  max_ram_mb: number;
  jvm_args: string[];
  skip_java_check: boolean;
  state: InstanceState;
  last_played_at?: string;
  total_play_seconds: number;
}

export interface CreateInstanceRequest {
  name: string;
  game_version: string;
  loader: LoaderType;
  java_path?: string;
}

export interface UpdateInstanceRequest {
  id: string;
  name?: string;
  java_path?: string;
  clear_java_path?: boolean;
  min_ram_mb?: number;
  max_ram_mb?: number;
  jvm_args?: string[];
  skip_java_check?: boolean;
}

export interface LaunchResponse {
  success: boolean;
  pid?: number;
  error?: string;
}

export interface AccountDTO {
  uuid: string;
  username: string;
  type: AccountType;
  is_active: boolean;
}

export interface ModItemDTO {
  id: string;
  slug: string;
  source: ModSource;
  name: string;
  author: string;
  summary: string;
  icon_url?: string;
  downloads: number;
  categories: string[];
}

export interface InstalledModDTO {
  file_name: string;
  mod_id?: string;
  name: string;
  version?: string;
  enabled: boolean;
  size_bytes: number;
}

export interface CrashReportDTO {
  category: string;
  summary: string;
  remedy: string;
  details: string;
  relevant_lines: string[];
  exit_code: number;
}

export interface SearchModsRequest {
  query: string;
  game_version: string;
  loader: string;
  source: ModSource;
  limit: number;
  offset: number;
  sort?: string;
  category?: string;
}

export interface SearchModsResultDTO {
  items: ModItemDTO[];
  total_count: number;
}

export interface ToggleModRequest {
  instance_id: string;
  file_name: string;
  enable: boolean;
}

export interface DeleteModRequest {
  instance_id: string;
  file_name: string;
}

export interface DownloadProgressEvent {
  task_id: string;
  file_name: string;
  bytes_read: number;
  total_bytes: number;
  percentage: number;
  speed_bps: number;
}

export interface LogLineEvent {
  instance_id: string;
  level: "info" | "warn" | "error" | "debug";
  message: string;
  timestamp: string;
}

export interface UpdateInfoDTO {
  has_update: boolean;
  version: string;
  current_version: string;
  release_date: string;
  release_notes: string;
  download_url: string;
  sha256: string;
  size: number;
}

export interface UpdateApplyResultDTO {
  success: boolean;
  message?: string;
  restart_required?: boolean;
}

export interface ListModVersionsRequest {
  instance_id?: string;
  mod_id: string;
  source: ModSource;
  game_version?: string;
  loader?: string;
}

export interface ModFileDTO {
  id: string;
  mod_id: string;
  file_name: string;
  display_name: string;
  release_type: string;
  file_size: number;
  file_date: string;
  game_versions: string[];
  loaders: string[];
  download_url: string;
}

export interface ModInstallProgressDTO {
  task_id: string;
  instance_id: string;
  mod_id: string;
  file_name: string;
  status: "idle" | "resolving_dependencies" | "downloading" | "verifying" | "completed" | "failed";
  bytes_read: number;
  total_bytes: number;
  percentage: number;
  error?: string;
}

export interface InstallModRequest {
  instance_id: string;
  mod_id: string;
  mod_slug: string;
  mod_name: string;
  source: ModSource;
  game_version: string;
  loader: string;
  version_id?: string;
}

export interface InstallModResponse {
  success: boolean;
  file_name: string;
  message: string;
}

export interface SetSettingRequest {
  key: string;
  value: string;
}

export interface GetSettingsResponse {
  settings: Record<string, string>;
}

export interface JavaInstallationDTO {
  path: string;
  home_dir: string;
  major_version: number;
  full_version: string;
  vendor: string;
  kind: "detected" | "managed";
  used_by: string[];
}

export interface JavaDownloadStatusDTO {
  task_id: string;
  major: number;
  status: "idle" | "downloading" | "extracting" | "ready" | "failed";
  bytes_read: number;
  total_bytes: number;
  percentage: number;
  error?: string;
}
