// Code generated by ipc/codegen/generate.go; DO NOT EDIT.

export type LoaderType = "vanilla" | "fabric" | "quilt" | "forge" | "neoforge";
export type InstanceState = "idle" | "downloading" | "launching" | "running" | "crashed";

export interface InstanceDTO {
  id: string;
  name: string;
  game_version: string;
  loader: LoaderType;
  loader_version?: string;
  icon_path?: string;
  state: InstanceState;
  total_play_seconds: number;
}

export interface CreateInstanceRequest {
  name: string;
  game_version: string;
  loader: LoaderType;
}

export interface LaunchResponse {
  success: boolean;
  pid?: number;
  error?: string;
}

export interface DownloadProgressEvent {
  task_id: string;
  file_name: string;
  bytes_read: number;
  total_bytes: number;
  percentage: number;
  speed_bps: number;
}

export interface LogLineEvent {
  instance_id: string;
  level: "info" | "warn" | "error" | "debug";
  message: string;
  timestamp: string;
}
