package main

import (
	"fmt"
	"os"
)

func main() {
	goContent := `// Code generated by ipc/codegen/generate.go; DO NOT EDIT.
package wails

import "time"

type InstanceDTO struct {
	ID               string     ` + "`" + `json:"id"` + "`" + `
	Name             string     ` + "`" + `json:"name"` + "`" + `
	GameVersion      string     ` + "`" + `json:"game_version"` + "`" + `
	Loader           string     ` + "`" + `json:"loader"` + "`" + `
	LoaderVersion    string     ` + "`" + `json:"loader_version,omitempty"` + "`" + `
	IconPath         string     ` + "`" + `json:"icon_path,omitempty"` + "`" + `
	JavaPath         string     ` + "`" + `json:"java_path,omitempty"` + "`" + `
	MinRAMMB         int        ` + "`" + `json:"min_ram_mb"` + "`" + `
	MaxRAMMB         int        ` + "`" + `json:"max_ram_mb"` + "`" + `
	JVMArgs          []string   ` + "`" + `json:"jvm_args"` + "`" + `
	SkipJavaCheck    bool       ` + "`" + `json:"skip_java_check"` + "`" + `
	State            string     ` + "`" + `json:"state"` + "`" + `
	LastPlayedAt     *time.Time ` + "`" + `json:"last_played_at,omitempty"` + "`" + `
	TotalPlaySeconds int64      ` + "`" + `json:"total_play_seconds"` + "`" + `
}

type CreateInstanceRequest struct {
	Name        string ` + "`" + `json:"name"` + "`" + `
	GameVersion string ` + "`" + `json:"game_version"` + "`" + `
	Loader      string ` + "`" + `json:"loader"` + "`" + `
	JavaPath    string ` + "`" + `json:"java_path,omitempty"` + "`" + `
}

type UpdateInstanceRequest struct {
	ID            string   ` + "`" + `json:"id"` + "`" + `
	Name          string   ` + "`" + `json:"name,omitempty"` + "`" + `
	JavaPath      string   ` + "`" + `json:"java_path,omitempty"` + "`" + `
	ClearJavaPath bool     ` + "`" + `json:"clear_java_path,omitempty"` + "`" + `
	MinRAMMB      int      ` + "`" + `json:"min_ram_mb,omitempty"` + "`" + `
	MaxRAMMB      int      ` + "`" + `json:"max_ram_mb,omitempty"` + "`" + `
	JVMArgs       []string ` + "`" + `json:"jvm_args,omitempty"` + "`" + `
	SkipJavaCheck *bool    ` + "`" + `json:"skip_java_check,omitempty"` + "`" + `
}

type LaunchResponse struct {
	Success bool   ` + "`" + `json:"success"` + "`" + `
	PID     int    ` + "`" + `json:"pid,omitempty"` + "`" + `
	Error   string ` + "`" + `json:"error,omitempty"` + "`" + `
}

type AccountDTO struct {
	UUID     string ` + "`" + `json:"uuid"` + "`" + `
	Username string ` + "`" + `json:"username"` + "`" + `
	Type     string ` + "`" + `json:"type"` + "`" + `
	IsActive bool   ` + "`" + `json:"is_active"` + "`" + `
}

type ModItemDTO struct {
	ID         string   ` + "`" + `json:"id"` + "`" + `
	Slug       string   ` + "`" + `json:"slug"` + "`" + `
	Source     string   ` + "`" + `json:"source"` + "`" + `
	Name       string   ` + "`" + `json:"name"` + "`" + `
	Author     string   ` + "`" + `json:"author"` + "`" + `
	Summary    string   ` + "`" + `json:"summary"` + "`" + `
	IconURL    string   ` + "`" + `json:"icon_url,omitempty"` + "`" + `
	Downloads  int64    ` + "`" + `json:"downloads"` + "`" + `
	Categories []string ` + "`" + `json:"categories"` + "`" + `
}

type InstalledModDTO struct {
	FileName  string ` + "`" + `json:"file_name"` + "`" + `
	ModID     string ` + "`" + `json:"mod_id,omitempty"` + "`" + `
	Name      string ` + "`" + `json:"name"` + "`" + `
	Version   string ` + "`" + `json:"version,omitempty"` + "`" + `
	Enabled   bool   ` + "`" + `json:"enabled"` + "`" + `
	SizeBytes int64  ` + "`" + `json:"size_bytes"` + "`" + `
}

type CrashReportDTO struct {
	Category      string   ` + "`" + `json:"category"` + "`" + `
	Summary       string   ` + "`" + `json:"summary"` + "`" + `
	Remedy        string   ` + "`" + `json:"remedy"` + "`" + `
	Details       string   ` + "`" + `json:"details"` + "`" + `
	RelevantLines []string ` + "`" + `json:"relevant_lines"` + "`" + `
	ExitCode      int      ` + "`" + `json:"exit_code"` + "`" + `
}

type SearchModsRequest struct {
	Query       string ` + "`" + `json:"query"` + "`" + `
	GameVersion string ` + "`" + `json:"game_version"` + "`" + `
	Loader      string ` + "`" + `json:"loader"` + "`" + `
	Source      string ` + "`" + `json:"source"` + "`" + `
	Limit       int    ` + "`" + `json:"limit"` + "`" + `
	Offset      int    ` + "`" + `json:"offset"` + "`" + `
	Sort        string ` + "`" + `json:"sort,omitempty"` + "`" + `
	Category    string ` + "`" + `json:"category,omitempty"` + "`" + `
}

type SearchModsResultDTO struct {
	Items      []ModItemDTO ` + "`" + `json:"items"` + "`" + `
	TotalCount int64        ` + "`" + `json:"total_count"` + "`" + `
}

type ToggleModRequest struct {
	InstanceID string ` + "`" + `json:"instance_id"` + "`" + `
	FileName   string ` + "`" + `json:"file_name"` + "`" + `
	Enable     bool   ` + "`" + `json:"enable"` + "`" + `
}

type DeleteModRequest struct {
	InstanceID string ` + "`" + `json:"instance_id"` + "`" + `
	FileName   string ` + "`" + `json:"file_name"` + "`" + `
}

type DownloadProgressEvent struct {
	TaskID     string  ` + "`" + `json:"task_id"` + "`" + `
	FileName   string  ` + "`" + `json:"file_name"` + "`" + `
	BytesRead  int64   ` + "`" + `json:"bytes_read"` + "`" + `
	TotalBytes int64   ` + "`" + `json:"total_bytes"` + "`" + `
	Percentage float64 ` + "`" + `json:"percentage"` + "`" + `
	SpeedBPS   int64   ` + "`" + `json:"speed_bps"` + "`" + `
}

type LogLineEvent struct {
	InstanceID string    ` + "`" + `json:"instance_id"` + "`" + `
	Level      string    ` + "`" + `json:"level"` + "`" + `
	Message    string    ` + "`" + `json:"message"` + "`" + `
	Timestamp  time.Time ` + "`" + `json:"timestamp"` + "`" + `
}

type UpdateInfoDTO struct {
	HasUpdate      bool      ` + "`" + `json:"has_update"` + "`" + `
	Version        string    ` + "`" + `json:"version"` + "`" + `
	CurrentVersion string    ` + "`" + `json:"current_version"` + "`" + `
	ReleaseDate    time.Time ` + "`" + `json:"release_date"` + "`" + `
	ReleaseNotes   string    ` + "`" + `json:"release_notes"` + "`" + `
	DownloadURL    string    ` + "`" + `json:"download_url"` + "`" + `
	SHA256         string    ` + "`" + `json:"sha256"` + "`" + `
	Size           int64     ` + "`" + `json:"size"` + "`" + `
}

type UpdateApplyResultDTO struct {
	Success         bool   ` + "`" + `json:"success"` + "`" + `
	Message         string ` + "`" + `json:"message,omitempty"` + "`" + `
	RestartRequired bool   ` + "`" + `json:"restart_required,omitempty"` + "`" + `
}

type ListModVersionsRequest struct {
	InstanceID  string ` + "`" + `json:"instance_id,omitempty"` + "`" + `
	ModID       string ` + "`" + `json:"mod_id"` + "`" + `
	Source      string ` + "`" + `json:"source"` + "`" + `
	GameVersion string ` + "`" + `json:"game_version,omitempty"` + "`" + `
	Loader      string ` + "`" + `json:"loader,omitempty"` + "`" + `
}

type ModFileDTO struct {
	ID           string   ` + "`" + `json:"id"` + "`" + `
	ModID        string   ` + "`" + `json:"mod_id"` + "`" + `
	FileName     string   ` + "`" + `json:"file_name"` + "`" + `
	DisplayName  string   ` + "`" + `json:"display_name"` + "`" + `
	ReleaseType  string   ` + "`" + `json:"release_type"` + "`" + `
	FileSize     int64    ` + "`" + `json:"file_size"` + "`" + `
	FileDate     string   ` + "`" + `json:"file_date"` + "`" + `
	GameVersions []string ` + "`" + `json:"game_versions"` + "`" + `
	Loaders      []string ` + "`" + `json:"loaders"` + "`" + `
	DownloadURL  string   ` + "`" + `json:"download_url"` + "`" + `
}

type ModInstallProgressDTO struct {
	TaskID     string ` + "`" + `json:"task_id"` + "`" + `
	InstanceID string ` + "`" + `json:"instance_id"` + "`" + `
	ModID      string ` + "`" + `json:"mod_id"` + "`" + `
	FileName   string ` + "`" + `json:"file_name"` + "`" + `
	Status     string ` + "`" + `json:"status"` + "`" + `
	BytesRead  int64  ` + "`" + `json:"bytes_read"` + "`" + `
	TotalBytes int64  ` + "`" + `json:"total_bytes"` + "`" + `
	Percentage int    ` + "`" + `json:"percentage"` + "`" + `
	Error      string ` + "`" + `json:"error,omitempty"` + "`" + `
}

type InstallModRequest struct {
	InstanceID  string ` + "`" + `json:"instance_id"` + "`" + `
	ModID       string ` + "`" + `json:"mod_id"` + "`" + `
	ModSlug     string ` + "`" + `json:"mod_slug"` + "`" + `
	ModName     string ` + "`" + `json:"mod_name"` + "`" + `
	Source      string ` + "`" + `json:"source"` + "`" + `
	GameVersion string ` + "`" + `json:"game_version"` + "`" + `
	Loader      string ` + "`" + `json:"loader"` + "`" + `
	VersionID   string ` + "`" + `json:"version_id,omitempty"` + "`" + `
}

type InstallModResponse struct {
	Success  bool   ` + "`" + `json:"success"` + "`" + `
	FileName string ` + "`" + `json:"file_name"` + "`" + `
	Message  string ` + "`" + `json:"message"` + "`" + `
}

type SetSettingRequest struct {
	Key   string ` + "`" + `json:"key"` + "`" + `
	Value string ` + "`" + `json:"value"` + "`" + `
}

type GetSettingsResponse struct {
	Settings map[string]string ` + "`" + `json:"settings"` + "`" + `
}

type JavaInstallationDTO struct {
	Path         string   ` + "`" + `json:"path"` + "`" + `
	HomeDir      string   ` + "`" + `json:"home_dir"` + "`" + `
	MajorVersion int      ` + "`" + `json:"major_version"` + "`" + `
	FullVersion  string   ` + "`" + `json:"full_version"` + "`" + `
	Vendor       string   ` + "`" + `json:"vendor"` + "`" + `
	Kind         string   ` + "`" + `json:"kind"` + "`" + `
	UsedBy       []string ` + "`" + `json:"used_by"` + "`" + `
}

type JavaDownloadStatusDTO struct {
	TaskID     string  ` + "`" + `json:"task_id"` + "`" + `
	Major      int     ` + "`" + `json:"major"` + "`" + `
	Status     string  ` + "`" + `json:"status"` + "`" + `
	BytesRead  int64   ` + "`" + `json:"bytes_read"` + "`" + `
	TotalBytes int64   ` + "`" + `json:"total_bytes"` + "`" + `
	Percentage float64 ` + "`" + `json:"percentage"` + "`" + `
	Error      string  ` + "`" + `json:"error,omitempty"` + "`" + `
}
`

	tsContent := `// Code generated by ipc/codegen/generate.go; DO NOT EDIT.

export type LoaderType = "vanilla" | "fabric" | "quilt" | "forge" | "neoforge";
export type InstanceState = "idle" | "downloading" | "launching" | "running" | "crashed";
export type AccountType = "microsoft" | "offline";
export type ModSource = "modrinth" | "curseforge";

export interface InstanceDTO {
  id: string;
  name: string;
  game_version: string;
  loader: LoaderType;
  loader_version?: string;
  icon_path?: string;
  java_path?: string;
  min_ram_mb: number;
  max_ram_mb: number;
  jvm_args: string[];
  skip_java_check: boolean;
  state: InstanceState;
  last_played_at?: string;
  total_play_seconds: number;
}

export interface CreateInstanceRequest {
  name: string;
  game_version: string;
  loader: LoaderType;
  java_path?: string;
}

export interface UpdateInstanceRequest {
  id: string;
  name?: string;
  java_path?: string;
  clear_java_path?: boolean;
  min_ram_mb?: number;
  max_ram_mb?: number;
  jvm_args?: string[];
  skip_java_check?: boolean;
}

export interface LaunchResponse {
  success: boolean;
  pid?: number;
  error?: string;
}

export interface AccountDTO {
  uuid: string;
  username: string;
  type: AccountType;
  is_active: boolean;
}

export interface ModItemDTO {
  id: string;
  slug: string;
  source: ModSource;
  name: string;
  author: string;
  summary: string;
  icon_url?: string;
  downloads: number;
  categories: string[];
}

export interface InstalledModDTO {
  file_name: string;
  mod_id?: string;
  name: string;
  version?: string;
  enabled: boolean;
  size_bytes: number;
}

export interface CrashReportDTO {
  category: string;
  summary: string;
  remedy: string;
  details: string;
  relevant_lines: string[];
  exit_code: number;
}

export interface SearchModsRequest {
  query: string;
  game_version: string;
  loader: string;
  source: ModSource;
  limit: number;
  offset: number;
  sort?: string;
  category?: string;
}

export interface SearchModsResultDTO {
  items: ModItemDTO[];
  total_count: number;
}

export interface ToggleModRequest {
  instance_id: string;
  file_name: string;
  enable: boolean;
}

export interface DeleteModRequest {
  instance_id: string;
  file_name: string;
}

export interface DownloadProgressEvent {
  task_id: string;
  file_name: string;
  bytes_read: number;
  total_bytes: number;
  percentage: number;
  speed_bps: number;
}

export interface LogLineEvent {
  instance_id: string;
  level: "info" | "warn" | "error" | "debug";
  message: string;
  timestamp: string;
}

export interface UpdateInfoDTO {
  has_update: boolean;
  version: string;
  current_version: string;
  release_date: string;
  release_notes: string;
  download_url: string;
  sha256: string;
  size: number;
}

export interface UpdateApplyResultDTO {
  success: boolean;
  message?: string;
  restart_required?: boolean;
}

export interface ListModVersionsRequest {
  instance_id?: string;
  mod_id: string;
  source: ModSource;
  game_version?: string;
  loader?: string;
}

export interface ModFileDTO {
  id: string;
  mod_id: string;
  file_name: string;
  display_name: string;
  release_type: string;
  file_size: number;
  file_date: string;
  game_versions: string[];
  loaders: string[];
  download_url: string;
}

export interface ModInstallProgressDTO {
  task_id: string;
  instance_id: string;
  mod_id: string;
  file_name: string;
  status: "idle" | "resolving_dependencies" | "downloading" | "verifying" | "completed" | "failed";
  bytes_read: number;
  total_bytes: number;
  percentage: number;
  error?: string;
}

export interface InstallModRequest {
  instance_id: string;
  mod_id: string;
  mod_slug: string;
  mod_name: string;
  source: ModSource;
  game_version: string;
  loader: string;
  version_id?: string;
}

export interface InstallModResponse {
  success: boolean;
  file_name: string;
  message: string;
}

export interface SetSettingRequest {
  key: string;
  value: string;
}

export interface GetSettingsResponse {
  settings: Record<string, string>;
}

export interface JavaInstallationDTO {
  path: string;
  home_dir: string;
  major_version: number;
  full_version: string;
  vendor: string;
  kind: "detected" | "managed";
  used_by: string[];
}

export interface JavaDownloadStatusDTO {
  task_id: string;
  major: number;
  status: "idle" | "downloading" | "extracting" | "ready" | "failed";
  bytes_read: number;
  total_bytes: number;
  percentage: number;
  error?: string;
}
`

	if err := os.WriteFile("internal/adapters/wails/ipc_types.go", []byte(goContent), 0644); err != nil {
		fmt.Printf("failed to write go types: %v\n", err)
		os.Exit(1)
	}

	_ = os.MkdirAll("frontend/src/bindings", 0755)
	if err := os.WriteFile("frontend/src/bindings/ipc_types.ts", []byte(tsContent), 0644); err != nil {
		fmt.Printf("failed to write ts types: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Contract-first IPC types generated successfully")
}