package main

import (
	"fmt"
	"os"
)

func main() {
	goContent := `// Code generated by ipc/codegen/generate.go; DO NOT EDIT.
package wails

import "time"

type InstanceDTO struct {
	ID               string ` + "`" + `json:"id"` + "`" + `
	Name             string ` + "`" + `json:"name"` + "`" + `
	GameVersion      string ` + "`" + `json:"game_version"` + "`" + `
	Loader           string ` + "`" + `json:"loader"` + "`" + `
	LoaderVersion    string ` + "`" + `json:"loader_version,omitempty"` + "`" + `
	IconPath         string ` + "`" + `json:"icon_path,omitempty"` + "`" + `
	State            string ` + "`" + `json:"state"` + "`" + `
	TotalPlaySeconds int64  ` + "`" + `json:"total_play_seconds"` + "`" + `
}

type CreateInstanceRequest struct {
	Name        string ` + "`" + `json:"name"` + "`" + `
	GameVersion string ` + "`" + `json:"game_version"` + "`" + `
	Loader      string ` + "`" + `json:"loader"` + "`" + `
}

type LaunchResponse struct {
	Success bool   ` + "`" + `json:"success"` + "`" + `
	PID     int    ` + "`" + `json:"pid,omitempty"` + "`" + `
	Error   string ` + "`" + `json:"error,omitempty"` + "`" + `
}

type AccountDTO struct {
	UUID     string ` + "`" + `json:"uuid"` + "`" + `
	Username string ` + "`" + `json:"username"` + "`" + `
	Type     string ` + "`" + `json:"type"` + "`" + `
	IsActive bool   ` + "`" + `json:"is_active"` + "`" + `
}

type ModItemDTO struct {
	ID         string   ` + "`" + `json:"id"` + "`" + `
	Slug       string   ` + "`" + `json:"slug"` + "`" + `
	Source     string   ` + "`" + `json:"source"` + "`" + `
	Name       string   ` + "`" + `json:"name"` + "`" + `
	Author     string   ` + "`" + `json:"author"` + "`" + `
	Summary    string   ` + "`" + `json:"summary"` + "`" + `
	IconURL    string   ` + "`" + `json:"icon_url,omitempty"` + "`" + `
	Downloads  int64    ` + "`" + `json:"downloads"` + "`" + `
	Categories []string ` + "`" + `json:"categories"` + "`" + `
}

type InstalledModDTO struct {
	FileName  string ` + "`" + `json:"file_name"` + "`" + `
	ModID     string ` + "`" + `json:"mod_id,omitempty"` + "`" + `
	Name      string ` + "`" + `json:"name"` + "`" + `
	Version   string ` + "`" + `json:"version,omitempty"` + "`" + `
	Enabled   bool   ` + "`" + `json:"enabled"` + "`" + `
	SizeBytes int64  ` + "`" + `json:"size_bytes"` + "`" + `
}

type CrashReportDTO struct {
	Category      string   ` + "`" + `json:"category"` + "`" + `
	Summary       string   ` + "`" + `json:"summary"` + "`" + `
	Remedy        string   ` + "`" + `json:"remedy"` + "`" + `
	Details       string   ` + "`" + `json:"details"` + "`" + `
	RelevantLines []string ` + "`" + `json:"relevant_lines"` + "`" + `
	ExitCode      int      ` + "`" + `json:"exit_code"` + "`" + `
}

type SearchModsRequest struct {
	Query       string ` + "`" + `json:"query"` + "`" + `
	GameVersion string ` + "`" + `json:"game_version"` + "`" + `
	Loader      string ` + "`" + `json:"loader"` + "`" + `
	Source      string ` + "`" + `json:"source"` + "`" + `
	Limit       int    ` + "`" + `json:"limit"` + "`" + `
	Offset      int    ` + "`" + `json:"offset"` + "`" + `
}

type ToggleModRequest struct {
	InstanceID string ` + "`" + `json:"instance_id"` + "`" + `
	FileName   string ` + "`" + `json:"file_name"` + "`" + `
	Enable     bool   ` + "`" + `json:"enable"` + "`" + `
}

type DeleteModRequest struct {
	InstanceID string ` + "`" + `json:"instance_id"` + "`" + `
	FileName   string ` + "`" + `json:"file_name"` + "`" + `
}

type DownloadProgressEvent struct {
	TaskID     string  ` + "`" + `json:"task_id"` + "`" + `
	FileName   string  ` + "`" + `json:"file_name"` + "`" + `
	BytesRead  int64   ` + "`" + `json:"bytes_read"` + "`" + `
	TotalBytes int64   ` + "`" + `json:"total_bytes"` + "`" + `
	Percentage float64 ` + "`" + `json:"percentage"` + "`" + `
	SpeedBPS   int64   ` + "`" + `json:"speed_bps"` + "`" + `
}

type LogLineEvent struct {
	InstanceID string    ` + "`" + `json:"instance_id"` + "`" + `
	Level      string    ` + "`" + `json:"level"` + "`" + `
	Message    string    ` + "`" + `json:"message"` + "`" + `
	Timestamp  time.Time ` + "`" + `json:"timestamp"` + "`" + `
}

type UpdateInfoDTO struct {
	HasUpdate      bool      ` + "`" + `json:"has_update"` + "`" + `
	Version        string    ` + "`" + `json:"version"` + "`" + `
	CurrentVersion string    ` + "`" + `json:"current_version"` + "`" + `
	ReleaseDate    time.Time ` + "`" + `json:"release_date"` + "`" + `
	ReleaseNotes   string    ` + "`" + `json:"release_notes"` + "`" + `
	DownloadURL    string    ` + "`" + `json:"download_url"` + "`" + `
	SHA256         string    ` + "`" + `json:"sha256"` + "`" + `
	Size           int64     ` + "`" + `json:"size"` + "`" + `
}

type UpdateApplyResultDTO struct {
	Success         bool   ` + "`" + `json:"success"` + "`" + `
	Message         string ` + "`" + `json:"message,omitempty"` + "`" + `
	RestartRequired bool   ` + "`" + `json:"restart_required,omitempty"` + "`" + `
}
`

	tsContent := `// Code generated by ipc/codegen/generate.go; DO NOT EDIT.

export type LoaderType = "vanilla" | "fabric" | "quilt" | "forge" | "neoforge";
export type InstanceState = "idle" | "downloading" | "launching" | "running" | "crashed";
export type AccountType = "microsoft" | "offline";
export type ModSource = "modrinth" | "curseforge";

export interface InstanceDTO {
  id: string;
  name: string;
  game_version: string;
  loader: LoaderType;
  loader_version?: string;
  icon_path?: string;
  state: InstanceState;
  total_play_seconds: number;
}

export interface CreateInstanceRequest {
  name: string;
  game_version: string;
  loader: LoaderType;
}

export interface LaunchResponse {
  success: boolean;
  pid?: number;
  error?: string;
}

export interface AccountDTO {
  uuid: string;
  username: string;
  type: AccountType;
  is_active: boolean;
}

export interface ModItemDTO {
  id: string;
  slug: string;
  source: ModSource;
  name: string;
  author: string;
  summary: string;
  icon_url?: string;
  downloads: number;
  categories: string[];
}

export interface InstalledModDTO {
  file_name: string;
  mod_id?: string;
  name: string;
  version?: string;
  enabled: boolean;
  size_bytes: number;
}

export interface CrashReportDTO {
  category: string;
  summary: string;
  remedy: string;
  details: string;
  relevant_lines: string[];
  exit_code: number;
}

export interface SearchModsRequest {
  query: string;
  game_version: string;
  loader: string;
  source: ModSource;
  limit: number;
  offset: number;
}

export interface ToggleModRequest {
  instance_id: string;
  file_name: string;
  enable: boolean;
}

export interface DeleteModRequest {
  instance_id: string;
  file_name: string;
}

export interface DownloadProgressEvent {
  task_id: string;
  file_name: string;
  bytes_read: number;
  total_bytes: number;
  percentage: number;
  speed_bps: number;
}

export interface LogLineEvent {
  instance_id: string;
  level: "info" | "warn" | "error" | "debug";
  message: string;
  timestamp: string;
}

export interface UpdateInfoDTO {
  has_update: boolean;
  version: string;
  current_version: string;
  release_date: string;
  release_notes: string;
  download_url: string;
  sha256: string;
  size: number;
}

export interface UpdateApplyResultDTO {
  success: boolean;
  message?: string;
  restart_required?: boolean;
}
`

	if err := os.WriteFile("internal/adapters/wails/ipc_types.go", []byte(goContent), 0644); err != nil {
		fmt.Printf("failed to write go types: %v\n", err)
		os.Exit(1)
	}

	_ = os.MkdirAll("frontend/src/bindings", 0755)
	if err := os.WriteFile("frontend/src/bindings/ipc_types.ts", []byte(tsContent), 0644); err != nil {
		fmt.Printf("failed to write ts types: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Contract-first IPC types generated successfully")
}