package main

import (
	"fmt"
	"os"
)

func main() {
	goContent := `// Code generated by ipc/codegen/generate.go; DO NOT EDIT.
package wails

import "time"

type InstanceDTO struct {
	ID               string ` + "`" + `json:"id"` + "`" + `
	Name             string ` + "`" + `json:"name"` + "`" + `
	GameVersion      string ` + "`" + `json:"game_version"` + "`" + `
	Loader           string ` + "`" + `json:"loader"` + "`" + `
	LoaderVersion    string ` + "`" + `json:"loader_version,omitempty"` + "`" + `
	IconPath         string ` + "`" + `json:"icon_path,omitempty"` + "`" + `
	State            string ` + "`" + `json:"state"` + "`" + `
	TotalPlaySeconds int64  ` + "`" + `json:"total_play_seconds"` + "`" + `
}

type CreateInstanceRequest struct {
	Name        string ` + "`" + `json:"name"` + "`" + `
	GameVersion string ` + "`" + `json:"game_version"` + "`" + `
	Loader      string ` + "`" + `json:"loader"` + "`" + `
}

type LaunchResponse struct {
	Success bool   ` + "`" + `json:"success"` + "`" + `
	PID     int    ` + "`" + `json:"pid,omitempty"` + "`" + `
	Error   string ` + "`" + `json:"error,omitempty"` + "`" + `
}

type DownloadProgressEvent struct {
	TaskID     string  ` + "`" + `json:"task_id"` + "`" + `
	FileName   string  ` + "`" + `json:"file_name"` + "`" + `
	BytesRead  int64   ` + "`" + `json:"bytes_read"` + "`" + `
	TotalBytes int64   ` + "`" + `json:"total_bytes"` + "`" + `
	Percentage float64 ` + "`" + `json:"percentage"` + "`" + `
	SpeedBPS   int64   ` + "`" + `json:"speed_bps"` + "`" + `
}

type LogLineEvent struct {
	InstanceID string    ` + "`" + `json:"instance_id"` + "`" + `
	Level      string    ` + "`" + `json:"level"` + "`" + `
	Message    string    ` + "`" + `json:"message"` + "`" + `
	Timestamp  time.Time ` + "`" + `json:"timestamp"` + "`" + `
}
`

	tsContent := `// Code generated by ipc/codegen/generate.go; DO NOT EDIT.

export type LoaderType = "vanilla" | "fabric" | "quilt" | "forge" | "neoforge";
export type InstanceState = "idle" | "downloading" | "launching" | "running" | "crashed";

export interface InstanceDTO {
  id: string;
  name: string;
  game_version: string;
  loader: LoaderType;
  loader_version?: string;
  icon_path?: string;
  state: InstanceState;
  total_play_seconds: number;
}

export interface CreateInstanceRequest {
  name: string;
  game_version: string;
  loader: LoaderType;
}

export interface LaunchResponse {
  success: boolean;
  pid?: number;
  error?: string;
}

export interface DownloadProgressEvent {
  task_id: string;
  file_name: string;
  bytes_read: number;
  total_bytes: number;
  percentage: number;
  speed_bps: number;
}

export interface LogLineEvent {
  instance_id: string;
  level: "info" | "warn" | "error" | "debug";
  message: string;
  timestamp: string;
}
`

	if err := os.WriteFile("internal/adapters/wails/ipc_types.go", []byte(goContent), 0644); err != nil {
		fmt.Printf("failed to write go types: %v\n", err)
		os.Exit(1)
	}

	_ = os.MkdirAll("frontend/src/bindings", 0755)
	if err := os.WriteFile("frontend/src/bindings/ipc_types.ts", []byte(tsContent), 0644); err != nil {
		fmt.Printf("failed to write ts types: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Contract-first IPC types generated successfully")
}
